### ISSUE TITLE
WTF is this

### ISSUE THREAD

**Issue by b00sher** [komeiji-satori/Dress#658]
I was just checking trending repos, 12.9k+ stars. Creator of this is a fucking genius

**Comment by kbqncf** [comment]
motherfucker,the same to me

**Comment by kbqncf** [comment]
motherfucker,the same to me

**Comment by kbqncf** [comment]
where is the founder,I just want to kill it

**Comment by nikoqw** [comment]
https://github.com/komeiji-satori/Dress/issues/651#issuecomment-541286417

**Comment by mayeths** [comment]
Drag queen. Enjoy it!🤣

**Comment by mayeths** [comment]
They said if anyone wants to learn programming(or do anything else), he MUST posts photos wearing skirts to show everyone. Sounds strange, but really funny

**Comment by b00sher** [comment]
@mayeths you used pronoun _he_ as a generic and didn't consider women's existence. Please watch your tongue!

**Comment by mayeths** [comment]
> Edit: haven't noticed that you are foreign, sorry for being a dick, but this is a serious issue to not have respect for women nowadays! Otherwise when pissed-off womankind will rule the world, history will remember you as a sexist. Do you want that to happen?

Apologize for my poor english, I have updated my comment.

**Comment by b00sher** [comment]
> Apologize for my poor english, I have updated my comment.

Wait, it confused me even more. Originally on Chinese was it  about *anyone* or only about *males*? Because if it was about *anyone*, this would be correct:

>They said if anyone wants to learn programming(or do anything else), **they** MUST posts photos wearing skirts to show everyone. Sounds strange, but really funny

But if was about *males*, your current edit is right if you didn't use the word *man* in its old meaning because in English, historically, in scientific communities the word *man* was used to identify human-beings in general, so if you used it in that meaning, it still sounds like you are sexist, and the word *human* would be more suitable. However, if you will use word human but don't change pronoun *he* it would be like, only males could be humans. 

Btw, I was just kidding, nobody takes a shit about women rights because we all know the rule 37 of the internet which says that they do not exist.

**Comment by mayeths** [comment]
>Originally on Chinese was it about anyone or only about males?

Nop, it's just my mistake, but we use "HE" to indicate a unknown person. We have「他，她，它」to indicate HE, SHE and IT, all of them pronounce "TA" -- which means you may be confused when someone say "TA". We always guess "s/he" from the context and it's not that difficult. For convenience, our ancestors use 他 (HE, also "TA") to refer to a specific but unidentified person. This's why I misuse "anyone" and "he".

**Comment by b00sher** [comment]
Wow, if it really is how I imagine it, there is a plenty background for ambiguous lexical jokes, like referring to somebody as "TA" like: "TA looks great today!" and after person respond to you, you just like "Oh, did you think I meant *TA*? I was talking about a flower over here)0))", that's cool (I'm 5 yo btw)!  I'm not familiar with any Asian languages and for me it's all looks like sticks with cute patterns (no offense).  

Comparing to many European languages, English is pretty neutral with [grammatical gender](https://en.wikipedia.org/wiki/Grammatical_gender#English), but we don't have 3rd person (he/she/it) neutral pronoun, so we often use [singular-they](https://en.wikipedia.org/wiki/Third-person_pronoun#Singular_they) instead: "Everyone _has_ to take off _their_ gloves before _they_ can have right to speak." I emphasized 'has' because 'everyone' considered to be singular as well, and when I used 'they' it had meaning of 3rd person pronoun, hence it can be substituted as 'he/she(/it)' ('their' -> 'his/her(/its)')

**Comment by Slept-Warrior** [comment]
@b00sher please allow me to correct a mistake in @mayeths 's explanation:
Chinese, or to be precise, Han characters, are Logosyllabic scripts([Wiki](https://en.wikipedia.org/wiki/Logogram)). The character '他' contains two parts, '亻' and '也'. '亻' means human, and '也' indicates that it's a third-person pronoun. Thus, '他' is gender-neutral in history. But there's a women-right movement back in 1920 that create the character '她' to specify the pronoun for third-person woman. Since then and only since then, '他' slowly becoming the pronoun for third-person man. 
Nowadays, the official dictionary of Han characters still explain the character '他' can be a gender-neutral pronoun for third-person human.

I know this is some kind of wording, but it never hurt to learn some new things tho :p

**Comment by mayeths** [comment]
@Slept-Warrior Great explanation with somewhat chinglish grammar  :3 🤣

**Comment by b00sher** [comment]
@Slept-Warrior thank you for the explanation. Wonder, why did they make another character but keep pronunciation? For instance, in Spanish there are 2 ways to say "they": "ellos/ellas", we use "ellos" when we don't know about about gender of a group members, and "ellas" when we are talking about a group of females.  

I'm not a native English speaker, there is nothing for you to apologize for, your English is pretty.

**Comment by Slept-Warrior** [comment]
@b00sher Sorry for the delay, was kinda busy lately.
Now about the thing you wondered: 
The pronunciation of a Chinese character is formed by an initial, an vowel and a tone. In Mandarin Chinese, there are 23 initials, 24 vowels and 4 tones, if you ignore that some initial and vowel can't combine, there will be 23*24*4 (2208) type of pronunciation only for a Chinese word. I guess it's the limitation that caused the pronoun pronunciation problem.

And some relevant fun fact: 
In some part of China people use different pronoun (with slightly different pronunciation) if they want to address someone respectfully. In those circumstances they use 您 (nin) instead of 你 (ni) when they talk about the second-person 'you', they use 怹 (tan) instead of 他 (ta) for the third person
